### PR TITLE
Update to karafka 1.4

### PR DESCRIPTION
**Pull request by hobbypunk90**
We updated your avro gem to work with the new karafka serialization structure.

### CODE REVIEW

**Comment by mensfeld** [comment]
Hey @hobbypunk90 thank you. I will look into this next week. Avro has been something I wanted to fix and upgrade before 2.0 and work will definitely help me!

**Comment by nijikon** [comment]
@hobbypunk90 thanks for this PR, this is something that I had on my to-do list for a while. I will try to review and merge this next week.

**Comment by mensfeld** [comment]
@nijikon do you have any ETA on this one, or do you want me to take over?

**Comment by nijikon** [comment]
@mensfeld sorry, got a bit distracted with other things. I will work on this, today and tomorrow. There are a couple of things that I need to think through.

**Comment by nijikon** [comment]
@hobbypunk90 Unfortunately, we are currently working on 2.0, and we won't be able to merge this PR. There are a couple of reasons for that. First, you are changing the name of the gem from `karafka-avro-parser` to `karafka-avro-serialization`. The second one is that this is an experimental code. It's not solid and battle-tested. I've put this on our roadmap after the 2.0 release.

**Comment by mensfeld** [comment]
@hobbypunk90 sorry it was never merged :pray: I totally lost if because avro gem is still experimental.

**Pull request closed without merging**
